-- 1) Lookup tables
create table if not exists training_types (
                                              id integer generated by default as identity primary key,
                                              name varchar(50) not null unique,
    constraint chk_training_types_name
    check (name in ('CARDIO', 'STRENGTH'))
    );

-- 2) Users
create table if not exists users (
                                     id bigint generated by default as identity primary key,
                                     active boolean not null,
                                     createdat timestamp(6) not null,
    updatedat timestamp(6),
    deletedat timestamp(6),
    firstname varchar(255) not null,
    lastname varchar(255) not null,
    username varchar(255) not null unique,
    password varchar(255) not null
    );

-- 3) Trainees
create table if not exists trainees (
                                        id bigint generated by default as identity primary key,
                                        user_id bigint not null unique,
                                        active boolean not null,
                                        address varchar(255),
    dateofbirth date,
    createdat timestamp(6) not null,
    updatedat timestamp(6),
    deletedat timestamp(6),
    constraint fk_trainees_user
    foreign key (user_id) references users(id)
    );

-- 4) Trainers
create table if not exists trainers (
                                        id bigint generated by default as identity primary key,
                                        user_id bigint not null unique,
                                        specialization integer not null,
                                        active boolean not null,
                                        createdat timestamp(6) not null,
    updatedat timestamp(6),
    deletedat timestamp(6),
    constraint fk_trainers_user
    foreign key (user_id) references users(id),
    constraint fk_trainers_training_type
    foreign key (specialization) references training_types(id)
    );

-- 5) Many-to-many: trainer <-> trainee
create table if not exists trainer_trainee (
                                               trainer_id bigint not null,
                                               trainee_id bigint not null,
                                               constraint pk_trainer_trainee primary key (trainer_id, trainee_id),
    constraint fk_trainer_trainee_trainer
    foreign key (trainer_id) references trainers(id),
    constraint fk_trainer_trainee_trainee
    foreign key (trainee_id) references trainees(id)
    );

-- 6) Trainings
create table if not exists trainings (
                                         id bigint generated by default as identity primary key,
                                         trainee_id bigint not null,
                                         trainer_id bigint not null,
                                         type_id integer not null,
                                         name varchar(150) not null,
    date date not null,
    duration integer not null,
    active boolean not null,
    createdat timestamp(6) not null,
    updatedat timestamp(6),
    deletedat timestamp(6),
    constraint fk_trainings_trainee
    foreign key (trainee_id) references trainees(id),
    constraint fk_trainings_trainer
    foreign key (trainer_id) references trainers(id),
    constraint fk_trainings_type
    foreign key (type_id) references training_types(id)
    );