spring.application.name=trainer-workload-service
server.port=8081

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

security.jwt.secret=ZmFrZV9qd3Rfc2VjcmV0X2tleV9mb3IvcHJvZA==
security.jwt.expiration-ms=3600000

management.endpoints.web.exposure.include=health,info

logging.level.root=INFO
logging.level.org.example=INFO

# ActiveMQ
spring.activemq.broker-url=tcp://localhost:61616
spring.activemq.user=admin
spring.activemq.password=admin
workload.messaging.enabled=true
