spring:
  application:
    name: trainer-workload-service
  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/trainers_db?authSource=admin
      database: trainers_db
  jackson:
    serialization:
      write-dates-as-timestamps: false
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

server:
  port: 8081

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

security:
  jwt:
    secret: ZmFpZV9qd3Rfc2VjcmV0X2tleV9mb3IvcHJvZA==
    expiration-ms: 3600000

workload:
  messaging:
    enabled: true

logging:
  level:
    root: INFO
    org.example: DEBUG
    org.springframework.data.mongodb: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [transactionId=%X{transactionId}] - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} [transactionId=%X{transactionId}] - %msg%n"
  file:
    name: app.log

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  endpoint:
    health:
      show-details: always