server.port=8080

db.url=jdbc:postgresql://localhost:5432/simpleDB
db.username=postgresql
db.password=postgresql
db.driverClassName=org.postgresql.Driver

db.jpa.ddlAuto=drop
db.jpa.dialect=org.hibernate.dialect.PostgreSQLDialect
db.jpa.showSql=false
db.jpa.formatSql=false
db.jpa.namingStrategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl

db.pool.maximumPoolSize=10
db.pool.minimumIdle=2
db.pool.connectionTimeout=30000
db.pool.idleTimeout=600000
db.pool.maxLifetime=1800000
